export {default as Login } from './Login'
export {default as Cadastro } from './Cadastro'
export {default as PaginaInicial } from './Home'
export {default as Obesidade } from './Obesidade'
export {default as Receitas } from './Receitas'
export {default as Sobre } from './Sobre'
export {default as Perfil } from './Perfil'